RESTAURANT_MENU = {
    "Kebab w bułce": 13,
    "Kebab na talerzu": 15,
    "Frytki": 8,
    "Rosół": 10,
    "Pizza Margarita 40 cm": 30,
    "Pizza Caprese 40 cm": 31,
    "Pizza 4 sery 40 cm": 28,
    "Pizza Calzone 40 cm": 40,
    "Pstrąg smażony": 20,
    "Żurek z kiełbasą": 15,
    "Trzy kromki chleba": 3,
    "Ketchup w kubełku": 2,
    "Sos Czosnkowy w kubełku": 2,
    "Herbata": 6,
    "Kawa": 6,
    "Pepsi 200 ml": 5,
    "Fanta 200 ml": 5,
    "Ice tea 200 ml": 5,
    "Sprite 200 ml": 5,
}
